apiVersion: v1
kind: Pod
metadata:
  name: sealed-secrets-backuper-test
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::762233771014:role/sealed-secrets-backuper-kubeaid-demo-aws
  labels:
    app: backup-sealed-secrets
spec:
  containers:
  - command:
    - /bin/bash
    - /mnt/script
    image: ghcr.io/obmondo/backup-sealed-secrets-keys:latest
    imagePullPolicy: IfNotPresent
    name: backup-sealed-secrets
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt
      name: scripts
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: sealed-secrets-controller
  serviceAccountName: sealed-secrets-controller
  terminationGracePeriodSeconds: 30
  volumes:
  - configMap:
      defaultMode: 420
      name: backup-sealed-secrets
    name: scripts
