name: e2e-giteas

x-gitea-healthcheck: &gitea-healthcheck
  healthcheck:
    test: [ "CMD-SHELL", "curl -kf https://localhost:3000/api/v1/version/ || exit 1" ]
    interval: 30s
    timeout: 10s
    retries: 3

services:

  enableitdk-gitea:
    container_name: enableitdk-gitea
    image: gitea/gitea:1.22.1-rootless
    hostname: enableitdk-gitea
    environment:
      GITEA__security__INSTALL_LOCK: true
        # Controls access to the installation page. When set to
        # true, the installation page is not accessible.
    volumes:
      - type: bind
        source: ./configs/gitea/enableit/app.ini
        target: /etc/gitea/app.ini
      - ../../certs/enableitdk-gitea.crt:/etc/ssl/certs/gitea.crt:ro
      - ../../certs/enableitdk-gitea.key:/etc/ssl/private/gitea.key:ro
    command:
      - bash
      - -c
      - |
        gitea migrate
        gitea admin user create \
          --username test --password password --email test@dummy.io \
          --admin
        exec /usr/local/bin/docker-entrypoint.sh
    ports:
      - 3001:3000
    <<: *gitea-healthcheck
