name: Release

# This Github Action workflow is triggered, when a new release is created.
on:
  release:
    types: [created]

jobs:
  build_and_publish_binaries:
    name: Build and publish binaries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create outputs directory
        run: mkdir -p ./outputs/trivy

      - name: Run Trivy vulnerability and secret scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          trivy-config: trivy.yaml
          format: sarif
          output: ./outputs/trivy/fs.sarif

      - name: Upload the scan result to CodeQL
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./outputs/trivy/fs.sarif
          category: fs

      - name: Detect IaC vulnerabilities and misconfigurations using Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          trivy-config: trivy.yaml
          format: sarif
          output: ./outputs/trivy/iac-and-config.sarif

      - name: Upload the scan result to CodeQL
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./outputs/trivy/iac-and-config.sarif
          category: iac-and-configurations

      - uses: wangyoucao577/go-release-action@v1
        with:
          project_path: ./cmd
          goos: linux
          goarch: amd64
          binary_name: kubeaid-bootstrap-script
          github_token: ${{ secrets.GITHUB_TOKEN }}
