name: Release

# This Github Action workflow is triggered, when a new release is created.
on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  scan_sourcecode:
    name: Scanning sourcecode to find vulberabilities, misconfigurations and exposed secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create outputs directory
        run: mkdir -p /tmp/trivy

      - name: Run Trivy security scan against the sourcecode
        id: security-scan
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: fs
          vuln-type: library
          scan-ref: .
          trivy-config: trivy.yaml
          format: table
          output: security-scan-result.txt

      - name: Append the security scan result to the job summary
        run: |
          {
            echo "### 🛡️ Sourcecode security scan result :"
            echo ""
            echo '```terraform'
            cat security-scan-result.txt
            echo '```'
          } >> $GITHUB_STEP_SUMMARY

  build_and_publish_binaries:
    name: Build and publish binary
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create outputs directory
        run: mkdir -p ./outputs/trivy

      - uses: wangyoucao577/go-release-action@v1
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: ./cmd
          binary_name: kubeaid-bootstrap-script-${{ matrix.goos }}-${{ matrix.goarch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          compress_assets: OFF
